import { resolve } from 'node:path'
import { defineConfig } from 'vitest/config'

// Source-plane resolution: every @deepseek-ai import maps to the monorepo src
// (see tsconfig.src.json). Vite's core alias applies to imports from any
// importer, including files inside the symlinked packages themselves, so the
// whole graph runs against source, never built lib/.
const root = import.meta.dirname

// Monorepo checkout the aliases below point into. Defaults to the sibling
// `deepseek-harness` checkout the link: devDependencies use; override with
// DEEPSEEK_HARNESS_ROOT for other layouts or CI.
const harnessRoot = process.env.DEEPSEEK_HARNESS_ROOT ?? resolve(root, '../deepseek-harness')
const alias = [
  { find: '@deepseek-ai/cordis', replacement: resolve(root, `${harnessRoot}/vendor/cordis/src/index.ts`) },
  { find: '@deepseek-ai/cosmokit', replacement: resolve(root, `${harnessRoot}/vendor/cosmokit/src/index.ts`) },
  { find: '@deepseek-ai/schemastery', replacement: resolve(root, `${harnessRoot}/vendor/schemastery/src/index.ts`) },
  { find: '@deepseek-ai/cordis-plugin-loader', replacement: resolve(root, `${harnessRoot}/vendor/loader/src/index.ts`) },
  { find: '@deepseek-ai/cordis-plugin-include', replacement: resolve(root, `${harnessRoot}/vendor/include/src/index.ts`) },
  { find: '@deepseek-ai/cordis-plugin-group', replacement: resolve(root, `${harnessRoot}/vendor/group/src/index.ts`) },
  { find: '@deepseek-ai/cordis-plugin-timer', replacement: resolve(root, `${harnessRoot}/vendor/timer/src/index.ts`) },
  { find: '@deepseek-ai/cordis-plugin-hmr', replacement: resolve(root, `${harnessRoot}/vendor/hmr/src/index.ts`) },
  { find: '@deepseek-ai/cordis-plugin-logger-console', replacement: resolve(root, `${harnessRoot}/vendor/logger-console/src/index.ts`) },
  { find: '@deepseek-ai/node-addon-landlock-run', replacement: resolve(root, `${harnessRoot}/native/landlock-run/packages/entry/src/index.ts`) },
  { find: '@deepseek-ai/dsh-invariants', replacement: resolve(root, `${harnessRoot}/packages/runtime-diagnostics/invariants/src/index.ts`) },
  { find: '@deepseek-ai/dsh-tool-call-timeout-policy', replacement: resolve(root, `${harnessRoot}/packages/guard/timeout-policy/src/index.ts`) },
  { find: '@deepseek-ai/dsh-tool-call-timeout-policy/invariant', replacement: resolve(root, `${harnessRoot}/packages/guard/timeout-policy/src/invariant.ts`) },
  { find: '@deepseek-ai/dsh-typert-registry', replacement: resolve(root, `${harnessRoot}/packages/typert/registry/src/index.ts`) },
  { find: '@deepseek-ai/dsh-typert-registry/client', replacement: resolve(root, `${harnessRoot}/packages/typert/registry/src/client/index.ts`) },
  { find: '@deepseek-ai/dsh-api-gateway', replacement: resolve(root, `${harnessRoot}/packages/api/gateway/src/index.ts`) },
  { find: '@deepseek-ai/dsh-api-gateway/client', replacement: resolve(root, `${harnessRoot}/packages/api/gateway/src/client/index.ts`) },
  { find: '@deepseek-ai/dsh-api-gateway/invariant', replacement: resolve(root, `${harnessRoot}/packages/api/gateway/src/invariant.ts`) },
  { find: '@deepseek-ai/dsh-api-gateway/types', replacement: resolve(root, `${harnessRoot}/packages/api/gateway/src/types.ts`) },
  { find: '@deepseek-ai/dsh-typert-protocol', replacement: resolve(root, `${harnessRoot}/packages/typert/protocol/src/index.ts`) },
  { find: '@deepseek-ai/dsh-typert-protocol/types', replacement: resolve(root, `${harnessRoot}/packages/typert/protocol/src/types.ts`) },
  { find: '@deepseek-ai/dsh-typert-loader', replacement: resolve(root, `${harnessRoot}/packages/typert/loader/src/index.ts`) },
  { find: '@deepseek-ai/dsh-session/invariant', replacement: resolve(root, `${harnessRoot}/packages/core/session/src/invariant.ts`) },
  { find: '@deepseek-ai/dsh-typert-registry/types', replacement: resolve(root, `${harnessRoot}/packages/typert/registry/src/types.ts`) },
  { find: '@deepseek-ai/dsh-typert-generator', replacement: resolve(root, `${harnessRoot}/packages/typert/generator/src/index.ts`) },
  { find: '@deepseek-ai/dsh-session/types', replacement: resolve(root, `${harnessRoot}/packages/core/session/src/types.ts`) },
  { find: '@deepseek-ai/dsh-session/surface', replacement: resolve(root, `${harnessRoot}/packages/core/session/src/surface.ts`) },
  { find: '@deepseek-ai/dsh-session-projection/types', replacement: resolve(root, `${harnessRoot}/packages/session/session-projection/src/types.ts`) },
  { find: '@deepseek-ai/dsh-tool-todo/types', replacement: resolve(root, `${harnessRoot}/packages/todo/tool-todo/src/types.ts`) },
  { find: '@deepseek-ai/dsh-tool-todo/client', replacement: resolve(root, `${harnessRoot}/packages/todo/tool-todo/src/client.ts`) },
  { find: '@deepseek-ai/dsh-session-title/types', replacement: resolve(root, `${harnessRoot}/packages/session/session-title/src/types.ts`) },
  { find: '@deepseek-ai/dsh-session-title/client', replacement: resolve(root, `${harnessRoot}/packages/session/session-title/src/client.ts`) },
  { find: '@deepseek-ai/dsh-session-stats/types', replacement: resolve(root, `${harnessRoot}/packages/session/session-stats/src/types.ts`) },
  { find: '@deepseek-ai/dsh-session-stats/client', replacement: resolve(root, `${harnessRoot}/packages/session/session-stats/src/client.ts`) },
  { find: '@deepseek-ai/dsh-plan-mode/types', replacement: resolve(root, `${harnessRoot}/packages/plan/plan-mode/src/types.ts`) },
  { find: '@deepseek-ai/dsh-plan-mode/client', replacement: resolve(root, `${harnessRoot}/packages/plan/plan-mode/src/client.ts`) },
  { find: '@deepseek-ai/dsh-agent-presets/types', replacement: resolve(root, `${harnessRoot}/packages/preset/agent-presets/src/types.ts`) },
  { find: '@deepseek-ai/dsh-pwsh-local', replacement: resolve(root, `${harnessRoot}/packages/shell/pwsh-local/src/index.ts`) },
  { find: '@deepseek-ai/dsh-tool-pwsh', replacement: resolve(root, `${harnessRoot}/packages/shell/tool-pwsh/src/index.ts`) },
  { find: '@deepseek-ai/dsh-shell-env', replacement: resolve(root, `${harnessRoot}/packages/shell/shell-env/src/index.ts`) },
  { find: '@deepseek-ai/dsh-cordis-host-runner', replacement: resolve(root, `${harnessRoot}/packages/extensions/cordis-host-runner/src/index.ts`) },
  { find: '@deepseek-ai/dsh-cordis-host-runner/types', replacement: resolve(root, `${harnessRoot}/packages/extensions/cordis-host-runner/src/types.ts`) },
  { find: '@deepseek-ai/dsh-goal/types', replacement: resolve(root, `${harnessRoot}/packages/goal/goal/src/types.ts`) },
  { find: '@deepseek-ai/dsh-goal/client', replacement: resolve(root, `${harnessRoot}/packages/goal/goal/src/client.ts`) },
  { find: '@deepseek-ai/dsh-llm/types', replacement: resolve(root, `${harnessRoot}/packages/llm/llm/src/types.ts`) },
  { find: '@deepseek-ai/dsh-llm/brand', replacement: resolve(root, `${harnessRoot}/packages/llm/llm/src/brand.ts`) },
  { find: '@deepseek-ai/dsh-llm-retry/types', replacement: resolve(root, `${harnessRoot}/packages/llm/llm-retry/src/types.ts`) },
  { find: '@deepseek-ai/dsh-workflow/types', replacement: resolve(root, `${harnessRoot}/packages/workflow/workflow/src/types.ts`) },
  { find: '@deepseek-ai/dsh-tool-workflow/types', replacement: resolve(root, `${harnessRoot}/packages/workflow/tool-workflow/src/types.ts`) },
  { find: '@deepseek-ai/dsh-llm/message', replacement: resolve(root, `${harnessRoot}/packages/llm/llm/src/message.ts`) },
  { find: '@deepseek-ai/dsh-commands/brand', replacement: resolve(root, `${harnessRoot}/packages/interaction/commands/src/brand.ts`) },
  { find: '@deepseek-ai/dsh-commands/types', replacement: resolve(root, `${harnessRoot}/packages/interaction/commands/src/types.ts`) },
  { find: '@deepseek-ai/dsh-jobs/brand', replacement: resolve(root, `${harnessRoot}/packages/jobs/jobs/src/brand.ts`) },
  { find: '@deepseek-ai/dsh-credentials/types', replacement: resolve(root, `${harnessRoot}/packages/credentials/credentials/src/types.ts`) },
  { find: '@deepseek-ai/dsh-settings/types', replacement: resolve(root, `${harnessRoot}/packages/settings/settings/src/types.ts`) },
  { find: '@deepseek-ai/dsh-api-remotes/types', replacement: resolve(root, `${harnessRoot}/packages/api/remotes/src/types.ts`) },
  { find: '@deepseek-ai/dsh-api-remotes/invariant', replacement: resolve(root, `${harnessRoot}/packages/api/remotes/src/invariant.ts`) },
  { find: '@deepseek-ai/dsh-compaction/checkpoint', replacement: resolve(root, `${harnessRoot}/packages/compaction/compaction/src/checkpoint.ts`) },
  { find: '@deepseek-ai/dsh-compaction/types', replacement: resolve(root, `${harnessRoot}/packages/compaction/compaction/src/types.ts`) },
  { find: '@deepseek-ai/dsh-tools/presentation', replacement: resolve(root, `${harnessRoot}/packages/core/tools/src/presentation.ts`) },
  { find: '@deepseek-ai/dsh-tools/types', replacement: resolve(root, `${harnessRoot}/packages/core/tools/src/types.ts`) },
  { find: '@deepseek-ai/dsh-tool-subagent-control/list-agents', replacement: resolve(root, `${harnessRoot}/packages/subagent/tool-subagent-control/src/list-agents.ts`) },
  { find: '@deepseek-ai/dsh-user-approval/types', replacement: resolve(root, `${harnessRoot}/packages/interaction/user-approval/src/types.ts`) },
  { find: '@deepseek-ai/dsh-user-questions/types', replacement: resolve(root, `${harnessRoot}/packages/interaction/user-questions/src/types.ts`) },
  { find: '@deepseek-ai/dsh-agent/types', replacement: resolve(root, `${harnessRoot}/packages/core/agent/src/types.ts`) },
  { find: '@deepseek-ai/dsh-agent/brand', replacement: resolve(root, `${harnessRoot}/packages/core/agent/src/brand.ts`) },
  { find: '@deepseek-ai/dsh-agent/invariant', replacement: resolve(root, `${harnessRoot}/packages/core/agent/src/invariant.ts`) },
  { find: '@deepseek-ai/dsh-scope/invariant', replacement: resolve(root, `${harnessRoot}/packages/core/scope/src/invariant.ts`) },
  { find: '@deepseek-ai/dsh-agent-loop/invariant', replacement: resolve(root, `${harnessRoot}/packages/core/agent-loop/src/invariant.ts`) },
  { find: '@deepseek-ai/dsh-*/invariant', replacement: resolve(root, `${harnessRoot}/packages/core/*/src/invariant.ts`) },
  { find: '@deepseek-ai/dsh-host-*/invariant', replacement: resolve(root, `${harnessRoot}/packages/host/*/src/invariant.ts`) },
  { find: '@deepseek-ai/dsh-client-*/invariant', replacement: resolve(root, `${harnessRoot}/packages/client/*/src/invariant.ts`) },
  { find: '@deepseek-ai/dsh-headless/startup', replacement: resolve(root, `${harnessRoot}/packages/bundle/headless/src/startup.ts`) },
  { find: '@deepseek-ai/dsh-web-app/startup', replacement: resolve(root, `${harnessRoot}/packages/bundle/web-app/src/startup.ts`) },
  { find: '@deepseek-ai/dsh-client-*/client', replacement: resolve(root, `${harnessRoot}/packages/client/*/src/client`) },
  { find: '@deepseek-ai/dsh-host-apiproxy', replacement: resolve(root, `${harnessRoot}/packages/host/apiproxy/src/index.ts`) },
  { find: '@deepseek-ai/dsh-host-directory-picker', replacement: resolve(root, `${harnessRoot}/packages/host/directory-picker/src/index.ts`) },
  { find: '@deepseek-ai/dsh-host-directory-picker/*', replacement: resolve(root, `${harnessRoot}/packages/host/directory-picker/src/*`) },
  { find: '@deepseek-ai/dsh-host-directory-picker-browse', replacement: resolve(root, `${harnessRoot}/packages/host/directory-picker-browse/src/index.ts`) },
  { find: '@deepseek-ai/dsh-host-directory-picker-browse/*', replacement: resolve(root, `${harnessRoot}/packages/host/directory-picker-browse/src/*`) },
  { find: '@deepseek-ai/dsh-host-directory-picker-native', replacement: resolve(root, `${harnessRoot}/packages/host/directory-picker-native/src/index.ts`) },
  { find: '@deepseek-ai/dsh-host-directory-picker-native/*', replacement: resolve(root, `${harnessRoot}/packages/host/directory-picker-native/src/*`) },
  { find: '@deepseek-ai/dsh-host-directory-picker-auto', replacement: resolve(root, `${harnessRoot}/packages/host/directory-picker-auto/src/index.ts`) },
  { find: '@deepseek-ai/dsh-host-directory-picker-auto/*', replacement: resolve(root, `${harnessRoot}/packages/host/directory-picker-auto/src/*`) },
  { find: '@deepseek-ai/dsh-host-apiproxy/client', replacement: resolve(root, `${harnessRoot}/packages/host/apiproxy/src/fetch/client.ts`) },
  { find: '@deepseek-ai/dsh-host-apiproxy/*', replacement: resolve(root, `${harnessRoot}/packages/host/apiproxy/src/*`) },
  { find: '@deepseek-ai/dsh-host-webserver', replacement: resolve(root, `${harnessRoot}/packages/host/webserver/src/index.ts`) },
  { find: '@deepseek-ai/dsh-host-frontend-static', replacement: resolve(root, `${harnessRoot}/packages/host/frontend-static/src/index.ts`) },
  { find: '@deepseek-ai/dsh-host-plugin-inventory', replacement: resolve(root, `${harnessRoot}/packages/host/plugin-inventory/src/index.ts`) },
  { find: '@deepseek-ai/dsh-host-plugin-inventory/types', replacement: resolve(root, `${harnessRoot}/packages/host/plugin-inventory/src/types.ts`) },
  { find: '@deepseek-ai/dsh-client-ui-slots', replacement: resolve(root, `${harnessRoot}/packages/client/ui-slots/src/index.ts`) },
  { find: '@deepseek-ai/dsh-client-ui-attachment', replacement: resolve(root, `${harnessRoot}/packages/client/ui-attachment/src/index.ts`) },
  { find: '@deepseek-ai/dsh-client-ui-primitives', replacement: resolve(root, `${harnessRoot}/packages/client/ui-primitives/src/index.ts`) },
  { find: '@deepseek-ai/dsh-client-schema-form', replacement: resolve(root, `${harnessRoot}/packages/client/schema-form/src/index.ts`) },
  { find: '@deepseek-ai/dsh-client-schema-form/invariant', replacement: resolve(root, `${harnessRoot}/packages/client/schema-form/src/invariant.ts`) },
  { find: '@deepseek-ai/dsh-client-web-react', replacement: resolve(root, `${harnessRoot}/packages/client/web-react/src/index.ts`) },
  { find: '@deepseek-ai/dsh-client-connection', replacement: resolve(root, `${harnessRoot}/packages/client/connection/src/index.ts`) },
  { find: '@deepseek-ai/dsh-api-remotes', replacement: resolve(root, `${harnessRoot}/packages/api/remotes/src/index.ts`) },
  { find: '@deepseek-ai/dsh-api-remotes/client', replacement: resolve(root, `${harnessRoot}/packages/api/remotes/src/client/index.ts`) },
  { find: '@deepseek-ai/dsh-client-hmr', replacement: resolve(root, `${harnessRoot}/packages/client/hmr/src/index.ts`) },
  { find: '@deepseek-ai/dsh-client-modules', replacement: resolve(root, `${harnessRoot}/packages/client/modules/src/index.ts`) },
  { find: '@deepseek-ai/dsh-client-runtime', replacement: resolve(root, `${harnessRoot}/packages/client/runtime/src/index.ts`) },
  { find: '@deepseek-ai/dsh-client-runtime/client', replacement: resolve(root, `${harnessRoot}/packages/client/runtime/src/client`) },
  { find: '@deepseek-ai/dsh-cordis-client-runner', replacement: resolve(root, `${harnessRoot}/packages/extensions/cordis-client-runner/src/index.ts`) },
  { find: '@deepseek-ai/dsh-cordis-client-runner/client', replacement: resolve(root, `${harnessRoot}/packages/extensions/cordis-client-runner/src/client`) },
  { find: '@deepseek-ai/dsh-cordis-client-runner/invariant', replacement: resolve(root, `${harnessRoot}/packages/extensions/cordis-client-runner/src/invariant.ts`) },
  { find: '@deepseek-ai/dsh-client-ui-cordis', replacement: resolve(root, `${harnessRoot}/packages/extensions/ui-cordis/src/index.ts`) },
  { find: '@deepseek-ai/dsh-client-ui-cordis/client', replacement: resolve(root, `${harnessRoot}/packages/extensions/ui-cordis/src/client`) },
  { find: '@deepseek-ai/dsh-client-ui-cordis/invariant', replacement: resolve(root, `${harnessRoot}/packages/extensions/ui-cordis/src/invariant.ts`) },
  { find: '@deepseek-ai/dsh-client-test-runtime', replacement: resolve(root, `${harnessRoot}/packages/test-support/client-runtime/src/index.ts`) },
  { find: '@deepseek-ai/dsh-client-test-runtime/invariant', replacement: resolve(root, `${harnessRoot}/packages/test-support/client-runtime/src/invariant.ts`) },
  { find: '@deepseek-ai/dsh-client-ui-layout', replacement: resolve(root, `${harnessRoot}/packages/client/ui-layout/src/index.ts`) },
  { find: '@deepseek-ai/dsh-client-ui-sidebar', replacement: resolve(root, `${harnessRoot}/packages/client/ui-sidebar/src/index.ts`) },
  { find: '@deepseek-ai/dsh-client-ui-conversation', replacement: resolve(root, `${harnessRoot}/packages/client/ui-conversation/src/index.ts`) },
  { find: '@deepseek-ai/dsh-client-ui-tool', replacement: resolve(root, `${harnessRoot}/packages/client/ui-tool/src/index.ts`) },
  { find: '@deepseek-ai/dsh-client-ui-deliverables', replacement: resolve(root, `${harnessRoot}/packages/client/ui-deliverables/src/index.ts`) },
  { find: '@deepseek-ai/dsh-client-ui-workflow-run', replacement: resolve(root, `${harnessRoot}/packages/client/ui-workflow-run/src/index.ts`) },
  { find: '@deepseek-ai/dsh-client-ui-input-trigger', replacement: resolve(root, `${harnessRoot}/packages/client/ui-input-trigger/src/index.ts`) },
  { find: '@deepseek-ai/dsh-client-ui-commands', replacement: resolve(root, `${harnessRoot}/packages/client/ui-commands/src/index.ts`) },
  { find: '@deepseek-ai/dsh-client-ui-model-selection', replacement: resolve(root, `${harnessRoot}/packages/client/ui-model-selection/src/index.ts`) },
  { find: '@deepseek-ai/dsh-client-ui-goal', replacement: resolve(root, `${harnessRoot}/packages/client/ui-goal/src/index.ts`) },
  { find: '@deepseek-ai/dsh-client-ui-message-feedback', replacement: resolve(root, `${harnessRoot}/packages/client/ui-message-feedback/src/index.ts`) },
  { find: '@deepseek-ai/dsh-client-ui-agent-preset', replacement: resolve(root, `${harnessRoot}/packages/client/ui-agent-preset/src/index.ts`) },
  { find: '@deepseek-ai/dsh-client-ui-permission-presets', replacement: resolve(root, `${harnessRoot}/packages/client/ui-permission-presets/src/index.ts`) },
  { find: '@deepseek-ai/dsh-client-ui-skill', replacement: resolve(root, `${harnessRoot}/packages/client/ui-skill/src/index.ts`) },
  { find: '@deepseek-ai/dsh-client-ui-subagent', replacement: resolve(root, `${harnessRoot}/packages/client/ui-subagent/src/index.ts`) },
  { find: '@deepseek-ai/dsh-client-ui-settings-plugins', replacement: resolve(root, `${harnessRoot}/packages/client/ui-settings-plugins/src/index.ts`) },
  { find: '@deepseek-ai/dsh-client-ui-jobs', replacement: resolve(root, `${harnessRoot}/packages/client/ui-jobs/src/index.ts`) },
  { find: '@deepseek-ai/dsh-client-ui-plan', replacement: resolve(root, `${harnessRoot}/packages/client/ui-plan/src/index.ts`) },
  { find: '@deepseek-ai/dsh-client-ui-user-questions', replacement: resolve(root, `${harnessRoot}/packages/client/ui-user-questions/src/index.ts`) },
  { find: '@deepseek-ai/dsh-client-ui-trajectory', replacement: resolve(root, `${harnessRoot}/packages/client/ui-trajectory/src/index.ts`) },
  { find: '@deepseek-ai/dsh-client-ui-workspace', replacement: resolve(root, `${harnessRoot}/packages/client/ui-workspace/src/index.ts`) },
  { find: '@deepseek-ai/dsh-client-ui-theme', replacement: resolve(root, `${harnessRoot}/packages/client/ui-theme/src/index.ts`) },
  { find: '@deepseek-ai/dsh-client-ui-settings', replacement: resolve(root, `${harnessRoot}/packages/client/ui-settings/src/index.ts`) },
  { find: '@deepseek-ai/dsh-client-ui-settings-general', replacement: resolve(root, `${harnessRoot}/packages/client/ui-settings-general/src/index.ts`) },
  { find: '@deepseek-ai/dsh-client-ui-settings-models', replacement: resolve(root, `${harnessRoot}/packages/client/ui-settings-models/src/index.ts`) },
  { find: '@deepseek-ai/dsh-client-ui-settings-plugin-inventory', replacement: resolve(root, `${harnessRoot}/packages/client/ui-settings-plugin-inventory/src/index.ts`) },
  { find: '@deepseek-ai/dsh-client-locale', replacement: resolve(root, `${harnessRoot}/packages/client/locale/src/index.ts`) },
  { find: '@deepseek-ai/dsh-client-web', replacement: resolve(root, `${harnessRoot}/packages/client/web/src/index.ts`) },
  { find: '@deepseek-ai/dsh-sdk-client', replacement: resolve(root, `${harnessRoot}/packages/sdk/client/src/index.ts`) },
  { find: '@deepseek-ai/dsh-sdk-protocol', replacement: resolve(root, `${harnessRoot}/packages/sdk/protocol/src/index.ts`) },
  { find: '@deepseek-ai/dsh-sdk-jsonrpc-server', replacement: resolve(root, `${harnessRoot}/packages/sdk/server/src/index.ts`) },
  { find: '@deepseek-ai/dsh-*', replacement: resolve(root, `${harnessRoot}/packages/core/*/src/index.ts`) },
  { find: '@deepseek-ai/dsh-session', replacement: resolve(root, `${harnessRoot}/packages/core/session/src/index.ts`) },
  { find: '@deepseek-ai/dsh-agent', replacement: resolve(root, `${harnessRoot}/packages/core/agent/src/index.ts`) },
  { find: '@deepseek-ai/dsh-agent-loop', replacement: resolve(root, `${harnessRoot}/packages/core/agent-loop/src/index.ts`) },
  { find: '@deepseek-ai/dsh-tools', replacement: resolve(root, `${harnessRoot}/packages/core/tools/src/index.ts`) },
  { find: '@deepseek-ai/dsh-llm', replacement: resolve(root, `${harnessRoot}/packages/llm/llm/src/index.ts`) },
  { find: '@deepseek-ai/dsh-system-prompt', replacement: resolve(root, `${harnessRoot}/packages/core/system-prompt/src/index.ts`) },
  { find: '@deepseek-ai/dsh-home-paths', replacement: resolve(root, `${harnessRoot}/packages/util/home-paths/src/index.ts`) },
  { find: '@deepseek-ai/dsh-scope', replacement: resolve(root, `${harnessRoot}/packages/core/scope/src/index.ts`) },
  { find: '@deepseek-ai/dsh-brand', replacement: resolve(root, `${harnessRoot}/packages/util/brand/src/index.ts`) },
  { find: '@deepseek-ai/dsh-attachment', replacement: resolve(root, `${harnessRoot}/packages/attachment/attachment/src/index.ts`) },
  { find: '@deepseek-ai/dsh-code-runtime', replacement: resolve(root, `${harnessRoot}/packages/code-runtime/code-runtime/src/index.ts`) },
  { find: '@deepseek-ai/dsh-code-runtime-worker-thread', replacement: resolve(root, `${harnessRoot}/packages/code-runtime/code-runtime-worker-thread/src/index.ts`) },
  { find: '@deepseek-ai/dsh-user-approval', replacement: resolve(root, `${harnessRoot}/packages/interaction/user-approval/src/index.ts`) },
  { find: '@deepseek-ai/dsh-timeout', replacement: resolve(root, `${harnessRoot}/packages/util/timeout/src/index.ts`) },
  { find: '@deepseek-ai/dsh-settings', replacement: resolve(root, `${harnessRoot}/packages/settings/settings/src/index.ts`) },
  { find: '@deepseek-ai/dsh-session-persistence', replacement: resolve(root, `${harnessRoot}/packages/session/session-persistence/src/index.ts`) },
  { find: '@deepseek-ai/dsh-timeout/types', replacement: resolve(root, `${harnessRoot}/packages/util/timeout/src/types.ts`) },
]

export default defineConfig({
  resolve: { alias },
  test: {
    include: ['tests/**/*.spec.ts'],
    environment: 'node',
  },
})
